from macro_platform.domain.models import DashboardConfig, DashboardWidget, SeriesDefinition


TRACKED_SERIES: list[SeriesDefinition] = [
    SeriesDefinition(
        id="fred:CPIAUCSL",
        source="fred",
        source_key="CPIAUCSL",
        title="US CPI All Items",
        topic="inflation",
        country="US",
        frequency="monthly",
        unit="Index 1982-84=100",
        seasonal_adjustment="SA",
        nominal_real="nominal",
        release_lag="~2 weeks",
        tags=["inflation", "us", "headline"],
    ),
    SeriesDefinition(
        id="fred:UNRATE",
        source="fred",
        source_key="UNRATE",
        title="US Unemployment Rate",
        topic="labor",
        country="US",
        frequency="monthly",
        unit="Percent",
        seasonal_adjustment="SA",
        nominal_real="real",
        release_lag="~1 week",
        tags=["labor", "us"],
    ),
    SeriesDefinition(
        id="fred:PAYEMS",
        source="fred",
        source_key="PAYEMS",
        title="US Nonfarm Payrolls",
        topic="labor",
        country="US",
        frequency="monthly",
        unit="Thousands of Persons",
        seasonal_adjustment="SA",
        nominal_real="real",
        release_lag="~1 week",
        tags=["labor", "us"],
    ),
    SeriesDefinition(
        id="fred:FEDFUNDS",
        source="fred",
        source_key="FEDFUNDS",
        title="Effective Federal Funds Rate",
        topic="policy",
        country="US",
        frequency="monthly",
        unit="Percent",
        seasonal_adjustment="NSA",
        nominal_real="nominal",
        release_lag="~1 month",
        tags=["policy", "rates", "us"],
    ),
    SeriesDefinition(
        id="fred:DGS10",
        source="fred",
        source_key="DGS10",
        title="US 10Y Treasury Yield",
        topic="rates",
        country="US",
        frequency="daily",
        unit="Percent",
        seasonal_adjustment="NSA",
        nominal_real="nominal",
        release_lag="1 day",
        tags=["rates", "us"],
    ),
    SeriesDefinition(
        id="fred:DGS2",
        source="fred",
        source_key="DGS2",
        title="US 2Y Treasury Yield",
        topic="rates",
        country="US",
        frequency="daily",
        unit="Percent",
        seasonal_adjustment="NSA",
        nominal_real="nominal",
        release_lag="1 day",
        tags=["rates", "us"],
    ),
    SeriesDefinition(
        id="bls:CUUR0000SA0",
        source="bls",
        source_key="CUUR0000SA0",
        title="US CPI-U All Items",
        topic="inflation",
        country="US",
        frequency="monthly",
        unit="Index 1982-84=100",
        seasonal_adjustment="NSA",
        nominal_real="nominal",
        release_lag="~2 weeks",
        tags=["inflation", "us", "bls"],
    ),
    SeriesDefinition(
        id="bls:LNS14000000",
        source="bls",
        source_key="LNS14000000",
        title="US Unemployment Rate (BLS)",
        topic="labor",
        country="US",
        frequency="monthly",
        unit="Percent",
        seasonal_adjustment="SA",
        nominal_real="real",
        release_lag="~1 week",
        tags=["labor", "us", "bls"],
    ),
    SeriesDefinition(
        id="ecb:FM/B.U2.EUR.4F.KR.MRR_FR.LEV",
        source="ecb",
        source_key="FM/B.U2.EUR.4F.KR.MRR_FR.LEV",
        title="ECB Main Refinancing Operations Rate",
        topic="policy",
        country="EA",
        frequency="daily",
        unit="Percent",
        seasonal_adjustment="NSA",
        nominal_real="nominal",
        release_lag="Event-driven",
        tags=["policy", "rates", "ecb", "euro-area"],
    ),
    SeriesDefinition(
        id="ecb:EXR/D.USD.EUR.SP00.A",
        source="ecb",
        source_key="EXR/D.USD.EUR.SP00.A",
        title="USD/EUR ECB Reference Rate",
        topic="fx",
        country="EA",
        frequency="daily",
        unit="USD per EUR",
        seasonal_adjustment="NSA",
        nominal_real="nominal",
        release_lag="1 day",
        tags=["fx", "ecb", "euro-area"],
    ),
    SeriesDefinition(
        id="world_bank:USA:NY.GDP.MKTP.CD",
        source="world_bank",
        source_key="NY.GDP.MKTP.CD",
        title="US GDP (current US$)",
        topic="growth",
        country="US",
        frequency="annual",
        unit="Current US$",
        nominal_real="nominal",
        tags=["growth", "cross-country"],
        provider_params={"country_code": "USA"},
    ),
    SeriesDefinition(
        id="world_bank:CHN:NY.GDP.MKTP.CD",
        source="world_bank",
        source_key="NY.GDP.MKTP.CD",
        title="China GDP (current US$)",
        topic="growth",
        country="CN",
        frequency="annual",
        unit="Current US$",
        nominal_real="nominal",
        tags=["growth", "cross-country"],
        provider_params={"country_code": "CHN"},
    ),
    SeriesDefinition(
        id="world_bank:EMU:NY.GDP.MKTP.CD",
        source="world_bank",
        source_key="NY.GDP.MKTP.CD",
        title="Euro Area GDP (current US$)",
        topic="growth",
        country="EA",
        frequency="annual",
        unit="Current US$",
        nominal_real="nominal",
        tags=["growth", "cross-country"],
        provider_params={"country_code": "EMU"},
    ),
    SeriesDefinition(
        id="world_bank:JPN:NY.GDP.MKTP.CD",
        source="world_bank",
        source_key="NY.GDP.MKTP.CD",
        title="Japan GDP (current US$)",
        topic="growth",
        country="JP",
        frequency="annual",
        unit="Current US$",
        nominal_real="nominal",
        tags=["growth", "cross-country"],
        provider_params={"country_code": "JPN"},
    ),
    SeriesDefinition(
        id="world_bank:GBR:NY.GDP.MKTP.CD",
        source="world_bank",
        source_key="NY.GDP.MKTP.CD",
        title="UK GDP (current US$)",
        topic="growth",
        country="GB",
        frequency="annual",
        unit="Current US$",
        nominal_real="nominal",
        tags=["growth", "cross-country"],
        provider_params={"country_code": "GBR"},
    ),
    SeriesDefinition(
        id="world_bank:CAN:NY.GDP.MKTP.CD",
        source="world_bank",
        source_key="NY.GDP.MKTP.CD",
        title="Canada GDP (current US$)",
        topic="growth",
        country="CA",
        frequency="annual",
        unit="Current US$",
        nominal_real="nominal",
        tags=["growth", "cross-country"],
        provider_params={"country_code": "CAN"},
    ),
    SeriesDefinition(
        id="world_bank:USA:FP.CPI.TOTL.ZG",
        source="world_bank",
        source_key="FP.CPI.TOTL.ZG",
        title="US CPI Inflation",
        topic="inflation",
        country="US",
        frequency="annual",
        unit="Percent",
        nominal_real="real",
        tags=["inflation", "cross-country"],
        provider_params={"country_code": "USA"},
    ),
    SeriesDefinition(
        id="world_bank:CHN:FP.CPI.TOTL.ZG",
        source="world_bank",
        source_key="FP.CPI.TOTL.ZG",
        title="China CPI Inflation",
        topic="inflation",
        country="CN",
        frequency="annual",
        unit="Percent",
        nominal_real="real",
        tags=["inflation", "cross-country"],
        provider_params={"country_code": "CHN"},
    ),
    SeriesDefinition(
        id="world_bank:EMU:FP.CPI.TOTL.ZG",
        source="world_bank",
        source_key="FP.CPI.TOTL.ZG",
        title="Euro Area CPI Inflation",
        topic="inflation",
        country="EA",
        frequency="annual",
        unit="Percent",
        nominal_real="real",
        tags=["inflation", "cross-country"],
        provider_params={"country_code": "EMU"},
    ),
    SeriesDefinition(
        id="imf:US:NGDP_RPCH",
        source="imf",
        source_key="NGDP_RPCH",
        title="US Real GDP Growth (IMF WEO)",
        topic="growth",
        country="US",
        frequency="annual",
        unit="Percent",
        nominal_real="real",
        release_lag="Periodic",
        tags=["growth", "imf", "us"],
        provider_params={"country_code": "US"},
    ),
    SeriesDefinition(
        id="imf:CN:NGDP_RPCH",
        source="imf",
        source_key="NGDP_RPCH",
        title="China Real GDP Growth (IMF WEO)",
        topic="growth",
        country="CN",
        frequency="annual",
        unit="Percent",
        nominal_real="real",
        release_lag="Periodic",
        tags=["growth", "imf", "china"],
        provider_params={"country_code": "CN"},
    ),
    SeriesDefinition(
        id="oecd:US:LRUN64TT",
        source="oecd",
        source_key="LRUN64TT",
        title="US Harmonised Unemployment Rate (OECD)",
        topic="labor",
        country="US",
        frequency="annual",
        unit="Percent",
        seasonal_adjustment="SA",
        nominal_real="real",
        release_lag="Periodic",
        tags=["labor", "oecd", "us"],
        provider_params={"endpoint": "https://stats.oecd.org/SDMX-JSON/data/MEI/USA.LRUN64TT.STSA.A?contentType=csv"},
    ),
    SeriesDefinition(
        id="oecd:EA:LRUN64TT",
        source="oecd",
        source_key="LRUN64TT",
        title="Euro Area Harmonised Unemployment Rate (OECD)",
        topic="labor",
        country="EA",
        frequency="annual",
        unit="Percent",
        seasonal_adjustment="SA",
        nominal_real="real",
        release_lag="Periodic",
        tags=["labor", "oecd", "euro-area"],
        provider_params={"endpoint": "https://stats.oecd.org/SDMX-JSON/data/MEI/EA19.LRUN64TT.STSA.A?contentType=csv"},
    ),
]

MARKET_UNIVERSE: list[dict[str, str]] = [
    {"ticker": "SPY", "asset_class": "equities"},
    {"ticker": "QQQ", "asset_class": "equities"},
    {"ticker": "TLT", "asset_class": "rates"},
    {"ticker": "GLD", "asset_class": "commodities"},
    {"ticker": "DBC", "asset_class": "commodities"},
    {"ticker": "UUP", "asset_class": "fx"},
    {"ticker": "BTC-USD", "asset_class": "crypto"},
]

DEFAULT_DASHBOARDS: list[DashboardConfig] = [
    DashboardConfig(
        id="global-macro-monitor",
        name="Global Macro Monitor",
        widgets=[
            DashboardWidget(kind="timeseries", title="US Inflation", series_ids=["fred:CPIAUCSL"]),
            DashboardWidget(kind="timeseries", title="US Labor", series_ids=["fred:UNRATE", "fred:PAYEMS"]),
            DashboardWidget(
                kind="timeseries",
                title="ECB Policy and FX",
                series_ids=["ecb:FM/B.U2.EUR.4F.KR.MRR_FR.LEV", "ecb:EXR/D.USD.EUR.SP00.A"],
            ),
            DashboardWidget(
                kind="cross_country",
                title="GDP Comparison",
                series_ids=[
                    "world_bank:USA:NY.GDP.MKTP.CD",
                    "world_bank:CHN:NY.GDP.MKTP.CD",
                    "world_bank:EMU:NY.GDP.MKTP.CD",
                ],
            ),
        ],
    ),
    DashboardConfig(
        id="cross-asset-monitor",
        name="Cross Asset Monitor",
        widgets=[
            DashboardWidget(
                kind="market_prices",
                title="Liquid Asset Basket",
                params={"tickers": [item["ticker"] for item in MARKET_UNIVERSE]},
            )
        ],
    ),
]


def validate_series_definitions(series: list[SeriesDefinition]) -> None:
    allowed_sources = {"fred", "bls", "ecb", "world_bank", "imf", "oecd"}
    ids_seen: set[str] = set()
    for item in series:
        if item.id in ids_seen:
            raise ValueError(f"Duplicate series id detected: {item.id}")
        ids_seen.add(item.id)
        if item.source not in allowed_sources:
            raise ValueError(
                f"Unsupported source '{item.source}' for series {item.id}. "
                "Allowed sources: fred, bls, ecb, world_bank, imf, oecd."
            )
        if item.source == "world_bank" and not item.provider_params.get("country_code"):
            raise ValueError(f"world_bank series {item.id} requires provider_params.country_code")
        if item.source == "imf" and not item.provider_params.get("country_code"):
            raise ValueError(f"imf series {item.id} requires provider_params.country_code")
        if item.source == "oecd":
            endpoint = item.provider_params.get("endpoint")
            if not endpoint:
                raise ValueError(f"oecd series {item.id} requires provider_params.endpoint")
            if not str(endpoint).startswith("http"):
                raise ValueError(f"oecd series {item.id} endpoint must be an absolute http(s) URL")
